---
jobs:
- name: frontend-test
  plan:
  - get: frontend
    trigger: true
  - task: frontend-test
    file: frontend/ci/scripts/frontend-test.sh

- name: frontend-package
  plan:
  - get: frontend
    trigger: true
    passed: [frontend-test]
  - task: frontend-package
    file: frontend/ci/scripts/frontend-package.sh

- name: backend-test
  plan:
  - get: backend
    trigger: true
  - task: backend-test
    file: backend/ci/scripts/backend-test.sh

- name: backend-package
  plan:
  - get: backend
    trigger: true
    passed: [backend-test]
  - task: backend-package
    file: backend/ci/scripts/backend-package.sh

- name: docker-web-install

- name: web-integration

- name: docker-resource-install

- name: resource-test

- name: release-candidate

- name: major

- name: minor

- name: ship-it

resources:
- name: version
  type: semver
  source:

- name: frontend
  type: git
  source:

- name: backend
  type: git
  source:

- name: docker-web-upstream
  type: docker-image
  source:
    repository: python
    tag: '3.6.4-alpine3.7'

- name: docker-resource-upstream
  type: docker-image
  source:
    repository: alpine
    tag: '3.7'
